CREATE TABLE `USER` (
	`email`	VARCHAR(100)	NOT NULL,
	`password`	VARCHAR(100)	NULL,
	`name`	VARCHAR(50)	NULL,
	`nickname`	VARCHAR(50)	NULL,
	`address`	VARCHAR(200)	NULL,
	`phone_num`	VARCHAR(20)	NULL,
	`profile_img`	VARCHAR(200)	NULL,
	`description`	VARCHAR(1000)	NULL,
	`age`	INT	NULL,
	`gender`	VARCHAR(2)	NULL,
	`rank`	VARCHAR(10)	NULL,
	`coupon`	INT	NULL,
	`bank_account`	VARCHAR(50)	NULL,
	`credit_card`	VARCHAR(50)	NULL,
	`created`	DATETIME	NULL,
	`updated`	DATETIME	NULL
);

CREATE TABLE `CLOTHES_AND_CLOTHES_CLASS` (
	`clothes_class_id`	INT	NOT NULL,
	`clothes_id`	INT	NOT NULL,
	`created`	DATETIME	NULL,
	`updated`	DATETIME	NULL
);

CREATE TABLE `USER_AND_CLOTHES` (
	`user_email`	VARCHAR(100)	NOT NULL,
	`clothes_id`	INT	NOT NULL,
	`in_closet`	BOOL	NULL,
	`created`	DATETIME	NULL,
	`updated`	DATETIME	NULL
);

CREATE TABLE `CLOTHES_CLASS` (
	`id`	INT	NOT NULL,
	`major`	VARCHAR(50)	NULL,
	`middle`	VARCHAR(50)	NULL,
	`minor`	VARCHAR(50)	NULL,
	`created`	DATETIME	NULL,
	`updated`	DATETIME	NULL
);

CREATE TABLE `CLOTHES_SPEC` (
	`id`	INT	NOT NULL,
	`clothes_id`	INT	NOT NULL,
	`color`	VARCHAR(10)	NULL,
	`size`	VARCHAR(10)	NULL,
	`created`	DATETIME	NULL,
	`updated`	DATETIME	NULL
);

CREATE TABLE `USER_AND_USER` (
	`follower_email`	VARCHAR(100)	NOT NULL,
	`following_email`	VARCHAR(100)	NULL
);

CREATE TABLE `POST` (
	`id`	INT	NOT NULL,
	`user_email`	VARCHAR(100)	NOT NULL,
	`type`	VARCHAR(100)	NULL,
	`title`	VARCHAR(100)	NULL,
	`content`	VARCHAR(2000)	NULL,
	`created`	DATETIME	NULL,
	`updated`	DATETIME	NULL
);

CREATE TABLE `COMMENT` (
	`id`	INT	NOT NULL,
	`post_id`	INT	NOT NULL,
	`user_email`	VARCHAR(100)	NOT NULL,
	`content`	VARCHAR(200)	NULL,
	`created`	DATETIME	NULL,
	`updated`	DATETIME	NULL
);

CREATE TABLE `USER_RESERVATION` (
	`id`	INT	NOT NULL,
	`user_email`	VARCHAR(100)	NOT NULL,
	`clothes_item_id`	INT	NOT NULL,
	`duration`	INT	NULL,
	`reserved_date`	DATETIME	NULL,
	`returned`	BOOL	NULL,
	`created`	DATETIME	NULL,
	`updated`	DATETIME	NULL
);

CREATE TABLE `CLOTHES_ITEM` (
	`id`	INT	NOT NULL,
	`clothes_spec_id`	INT	NOT NULL,
	`status`	VARCHAR(30)	NULL,
	`created`	DATETIME	NULL,
	`updated`	DATETIME	NULL
);

CREATE TABLE `CLOTHES` (
	`id`	INT	NOT NULL,
	`brand`	VARCHAR(50)	NULL,
	`code_name`	VARCHAR(50)	NULL,
	`season`	VARCHAR(100)	NULL,
	`use`	VARCHAR(100)	NULL,
	`created`	DATETIME	NULL,
	`updated`	DATETIME	NULL
);

ALTER TABLE `USER` ADD CONSTRAINT `PK_USER` PRIMARY KEY (
	`email`
);

ALTER TABLE `CLOTHES_AND_CLOTHES_CLASS` ADD CONSTRAINT `PK_CLOTHES_AND_CLOTHES_CLASS` PRIMARY KEY (
	`clothes_class_id`,
	`clothes_id`
);

ALTER TABLE `USER_AND_CLOTHES` ADD CONSTRAINT `PK_USER_AND_CLOTHES` PRIMARY KEY (
	`user_email`,
	`clothes_id`
);

ALTER TABLE `CLOTHES_CLASS` ADD CONSTRAINT `PK_CLOTHES_CLASS` PRIMARY KEY (
	`id`
);

ALTER TABLE `CLOTHES_SPEC` ADD CONSTRAINT `PK_CLOTHES_SPEC` PRIMARY KEY (
	`id`,
	`clothes_id`
);

ALTER TABLE `USER_AND_USER` ADD CONSTRAINT `PK_USER_AND_USER` PRIMARY KEY (
	`follower_email`
);

ALTER TABLE `POST` ADD CONSTRAINT `PK_POST` PRIMARY KEY (
	`id`,
	`user_email`
);

ALTER TABLE `COMMENT` ADD CONSTRAINT `PK_COMMENT` PRIMARY KEY (
	`id`,
	`post_id`,
	`user_email`
);

ALTER TABLE `USER_RESERVATION` ADD CONSTRAINT `PK_USER_RESERVATION` PRIMARY KEY (
	`id`,
	`user_email`,
	`clothes_item_id`
);

ALTER TABLE `CLOTHES_ITEM` ADD CONSTRAINT `PK_CLOTHES_ITEM` PRIMARY KEY (
	`id`,
	`clothes_spec_id`
);

ALTER TABLE `CLOTHES` ADD CONSTRAINT `PK_CLOTHES` PRIMARY KEY (
	`id`
);

ALTER TABLE `CLOTHES_AND_CLOTHES_CLASS` ADD CONSTRAINT `FK_CLOTHES_CLASS_TO_CLOTHES_AND_CLOTHES_CLASS_1` FOREIGN KEY (
	`clothes_class_id`
)
REFERENCES `CLOTHES_CLASS` (
	`id`
);

ALTER TABLE `CLOTHES_AND_CLOTHES_CLASS` ADD CONSTRAINT `FK_CLOTHES_TO_CLOTHES_AND_CLOTHES_CLASS_1` FOREIGN KEY (
	`clothes_id`
)
REFERENCES `CLOTHES` (
	`id`
);

ALTER TABLE `USER_AND_CLOTHES` ADD CONSTRAINT `FK_USER_TO_USER_AND_CLOTHES_1` FOREIGN KEY (
	`user_email`
)
REFERENCES `USER` (
	`email`
);

ALTER TABLE `USER_AND_CLOTHES` ADD CONSTRAINT `FK_CLOTHES_TO_USER_AND_CLOTHES_1` FOREIGN KEY (
	`clothes_id`
)
REFERENCES `CLOTHES` (
	`id`
);

ALTER TABLE `CLOTHES_SPEC` ADD CONSTRAINT `FK_CLOTHES_TO_CLOTHES_SPEC_1` FOREIGN KEY (
	`clothes_id`
)
REFERENCES `CLOTHES` (
	`id`
);

ALTER TABLE `USER_AND_USER` ADD CONSTRAINT `FK_USER_TO_USER_AND_USER_1` FOREIGN KEY (
	`follower_email`
)
REFERENCES `USER` (
	`email`
);

ALTER TABLE `POST` ADD CONSTRAINT `FK_USER_TO_POST_1` FOREIGN KEY (
	`user_email`
)
REFERENCES `USER` (
	`email`
);

ALTER TABLE `COMMENT` ADD CONSTRAINT `FK_POST_TO_COMMENT_1` FOREIGN KEY (
	`post_id`
)
REFERENCES `POST` (
	`id`
);

ALTER TABLE `COMMENT` ADD CONSTRAINT `FK_USER_TO_COMMENT_1` FOREIGN KEY (
	`user_email`
)
REFERENCES `USER` (
	`email`
);

ALTER TABLE `USER_RESERVATION` ADD CONSTRAINT `FK_USER_TO_USER_RESERVATION_1` FOREIGN KEY (
	`user_email`
)
REFERENCES `USER` (
	`email`
);

ALTER TABLE `USER_RESERVATION` ADD CONSTRAINT `FK_CLOTHES_ITEM_TO_USER_RESERVATION_1` FOREIGN KEY (
	`clothes_item_id`
)
REFERENCES `CLOTHES_ITEM` (
	`id`
);

ALTER TABLE `CLOTHES_ITEM` ADD CONSTRAINT `FK_CLOTHES_SPEC_TO_CLOTHES_ITEM_1` FOREIGN KEY (
	`clothes_spec_id`
)
REFERENCES `CLOTHES_SPEC` (
	`id`
);

